feat: first basic-functions example
parodos-dev/serverless-workflow-examples pull request #1
Opened 2023-09-11 13:26 UTC by eloycoto

A small example, where it shows a few things:

- OpenAPI is not used because token cannot be set on the arguments.
- Some openapi issues has been reported: https://github.com/quarkiverse/quarkus-openapi-generator/issues/460
- Basic example where a branch in a GH repo is created
- Basic java CDI example too

2023-09-12 07:45 UTC, gabriel-farache commented on basic-functions/src/main/resources/workflow.sw.json
> +        }
Nice, I was wondering how we could manager error in a good manner.

This error is to catch java error from `isValidUser` and only that so maybe the name of the branch should be `invalidUserBranch` instead of `invalidBranch` for clarity sake.

If an error occurs when executing the rest actions, is there a way to handle the error as well? IIRC will not have the error message stored in the DI if anything happens whereas with invalid branches we could log the error message

2023-09-12 07:45 UTC, gabriel-farache commented on basic-functions/src/main/resources/workflow.sw.json
> +    },
that function is not used, right?

2023-09-12 07:45 UTC, gabriel-farache commented on basic-functions/README.md
> +- Sample OpenAPI functions from GitHub using custom REST to be able to get the token from the user.
would be nice to know which scopes the token have to have

2023-09-12 09:50 UTC, eloycoto commented on basic-functions/src/main/resources/workflow.sw.json
> +    },
No, it's just the example for now :-)

2023-09-12 09:50 UTC, eloycoto commented on basic-functions/README.md
> +- Sample OpenAPI functions from GitHub using custom REST to be able to get the token from the user.
I'll add it to the readme!

2023-09-13 07:27 UTC, gciavarrini requested changes

2023-09-13 07:27 UTC, gciavarrini commented on basic-functions/README.md
> +    "url": "https://api.github.com/repos/eloycoto/dotfiles/git/refs/heads/testTest-jo-merda",
Maybe it is better to change the url... :)

2023-09-13 07:27 UTC, gciavarrini commented on basic-functions/pom.xml
> +    <dependencies>
Do you think that can be useful to specify in the README which `kogito` dependencies you added and why?

2023-09-13 07:27 UTC, gciavarrini commented on basic-functions/src/main/resources/schemas/input.json
> +
nit: extra line

2023-09-13 09:36 UTC, masayag commented
@eloycoto based on https://github.com/quarkiverse/quarkus-openapi-generator/issues/460#issuecomment-1716121886 the issues seem to be solved. Not sure when it will be released, but perhaps we can switch to openapi to verify it?

2023-09-13 09:43 UTC, masayag commented on basic-functions/src/main/resources/workflow.sw.json
> +{
General question: Is there a reason behind using json and not yaml?

2023-09-13 09:43 UTC, masayag commented on basic-functions/src/main/resources/workflow.sw.json
> +  "id": "hello",
just a thought to reduce chances of colliding with other examples - a different workflow ID, something more concrete to the exaple?

2023-09-13 09:43 UTC, masayag commented on basic-functions/src/main/resources/workflow.sw.json
> +              "message": "Branch cannot be created"
is there an option to include the error message origninated by the exception?

2023-09-13 09:43 UTC, masayag commented on basic-functions/src/main/resources/schemas/input.json
> +        "base_branch": {
not related to this PR, but is the base_branch is the name of the argument as presented in the render workflow input form in backstage?
and does the description appears there as well? If yes, then I'd write the description without referring to a name of a a specific variable, but simply as: 
`"description": "the base branch to be used for creating the repository",` (or something like that).

2023-09-13 14:04 UTC, eloycoto commented
> @eloycoto based on [quarkiverse/quarkus-openapi-generator#460 (comment)](https://github.com/quarkiverse/quarkus-openapi-generator/issues/460#issuecomment-1716121886) the issues seem to be solved. Not sure when it will be released, but perhaps we can switch to openapi to verify it?

Sadly no, with openapi you cannot add the token from the workflow, need to use rest. Asked the team already

2023-09-13 16:05 UTC, eloycoto commented on basic-functions/src/main/resources/workflow.sw.json
> +  "id": "hello",
fixed in the yaml

2023-09-13 16:05 UTC, eloycoto commented on basic-functions/src/main/resources/schemas/input.json
> +        "base_branch": {
fixed on the yaml.

2023-09-14 07:43 UTC, gciavarrini approved these changes
lgtm

2023-09-14 08:29 UTC, merged