Flpath939 - ServiceNow workflow example
parodos-dev/serverless-workflow-examples pull request #31
Opened 2024-03-14 19:10 UTC by rhkp

Hi @dmartinol ,
Please find this PR for approval and let me know what you think? It contains following:

- ServiceNow instance setup instructions ( manual self-guided and automated ).
- Escalation workflow with integration with notifications service including readme's.

Let me know what you think or please approve?

Thanks

2024-03-15 07:41 UTC, dmartinol commented on escalation-sn/instance-setup/setup-script/readme.md
> +./clear-data.sh
I can;t see this script in the commit, missed it?

2024-03-15 07:59 UTC, dmartinol commented on escalation-sn/pom.xml
> +<project
you should use the swf-parent pom to inherit common properties and configs

2024-03-15 08:00 UTC, dmartinol commented on escalation-sn/src/main/resources/application.properties
> +# Application properties
for the sake of simplifying the production environment, pls separate the dev properties like quarkus.http.host in a application-dev.properties that will be ignored when building the production image

2024-03-15 08:02 UTC, dmartinol commented on escalation-sn/src/main/resources/specs/notifications.yaml
the notifications API should be pulled from the GitHub repo instead. Look [here](https://github.com/parodos-dev/serverless-workflows/blob/36a5b815131df73b0e0625bbf7fcb079d93005ba/escalation/ticketEscalation.sw.yaml#L11)

2024-03-15 08:02 UTC, dmartinol reviewed
some minor changes, pls review

2024-03-15 08:22 UTC, gabriel-farache requested changes
Few comments but nicely done!

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/instance-setup/setup-script/readme.md
> +./clear-data.sh
Yeah the file is in the .gitignore...
But I guess it's because the script is generated by the script:
> The instance setup script execution also generates a `clear-data.sh` script

But why something generated? What is changing between 2 executions?

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/README.md
> +curl -X POST http://localhost:7007/api/notifications/notifications -H "Content-Type: application/json" -d '{"title": "My message title", "message": "I have nothing to say", "origin": "my-origin", "ta
can be worthy to provide a curl command to GET the created message too

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/README.md
> +* After this wait, login to notifications service's postgres database console.
you are talking about the backstage notifications plugin, right? Why not simply send GET requests instead of looking into the DB?

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/README.md
> + 3e9cd0a6-c4c8-4ea1-973a-dbb063279397 | Manager, thanks a ton for approving this change request: CHG0030045
for approving this change request: <id> => for approving the change request: <id>

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/instance-setup/setup-script/readme.md
why `setup-script`? It's not consistent with `manual-self-guided` and the words used in the README:
> * [Automated approach](setup-script/readme.md)
> * [Manual approach](manual-self-guided/readme.md)

I would name the folder `automated-script` instead, what do you think?

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/src/main/resources/servicenow-escalation-schema.json
please put this file in a new folder names `schemas` for consistency across workflows

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +      - condition: (.readChangeRequest.result.state != "-5")
is there any other state we might want to consider? Ie: request cancelled, or pending maybe? So we can provide feedback to the user and stop the workflow?

I know that in the worst case scenario, the workflow timeout of 24h will prevent endless loop but until then it will consume resources every 30sec to check

2024-03-15 08:22 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            message: "\"Manager, thanks a ton for approving this change request: \\(.createdChangeRequest.result.number)\""
Manager, thanks a ton for approving this change request => Manager, thanks a ton for approving **the** change request

2024-03-15 09:17 UTC, gabriel-farache commented on escalation-sn/README.md
> +    * In the current implementation this reminder is generated every `30s` by the workflow.
I do not think we can do that in a workflow currently, cc @dmartinol I think you had the same issue a while back?

2024-03-15 14:58 UTC, rhkp commented on escalation-sn/instance-setup/setup-script/readme.md
I agree, renamed.

2024-03-15 15:01 UTC, rhkp commented on escalation-sn/README.md
> +    * In the current implementation this reminder is generated every `30s` by the workflow.
I agree @gabriel-farache, I think there is an issue open with SWF team to handle this ask.

2024-03-15 15:04 UTC, rhkp commented on escalation-sn/README.md
> +* Janus-idp notifications service is deployed and functionally running with instructions [found here](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/notifications-backend).
Currently when janus-idp runs the notification service is not deployed. I have to manually make it running as a static plugin with changes suggested at: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/notifications-backend

2024-03-15 15:06 UTC, rhkp commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +      - condition: (.readChangeRequest.result.state != "-5")
I think the state values are ServiceNow instance specific so to keep it straight forward I have made use of one state.

2024-03-15 15:26 UTC, rhkp commented on escalation-sn/src/main/resources/specs/notifications.yaml
Done

2024-03-15 15:27 UTC, rhkp commented on escalation-sn/README.md
> + 3e9cd0a6-c4c8-4ea1-973a-dbb063279397 | Manager, thanks a ton for approving this change request: CHG0030045
We will include curl commands to get messages from notifications plugin.

2024-03-15 15:43 UTC, rhkp commented on escalation-sn/pom.xml
> +<project
I think this will be not applicable in this case? The path of this project is `serverless-workflow-examples/escalation-sn`. Thus this is an independent maven pom project and does not have a parent.

2024-03-15 16:46 UTC, dmartinol commented on escalation-sn/pom.xml
> +<project
There is no aggregated pom.xml in this project (a flaw in the design 😞 ), but you can just add this to inherit from the parent:
```
  <parent>
    <groupId>dev.parodos</groupId>
    <artifactId>swf-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../swf-parent</relativePath>
  </parent>
```
Please also simplify the pom.xml and remove duplicated definitions already set in the parent.

2024-03-15 17:49 UTC, rhkp commented on escalation-sn/pom.xml
> +<project
Okay great, I have done this. However I had to keep the following properties otherwise even though they are defined in the parent pom, I am seeing many errors with compile/run.

`
<kogito.bom.version>1.43.0.Final</kogito.bom.version>
<quarkus.platform.version>2.16.10.Final</quarkus.platform.version>
`

2024-03-15 18:00 UTC, rhkp commented on escalation-sn/src/main/resources/application.properties
> +# Application properties
@dmartinol Is there another example where this is done?

I have added the following one's to the `application-dev.properties` file. However if other properties need to be moved to application-dev.properties, do let me know.

`
#Quarkus
quarkus.http.host=0.0.0.0
# This is to enable debugging of HTTP request 
quarkus.log.category.\"org.apache.http\".level=DEBUG

# Added
quarkus.http.port=8080
`

2024-03-15 18:16 UTC, rhkp commented on escalation-sn/README.md
> + 3e9cd0a6-c4c8-4ea1-973a-dbb063279397 | Manager, thanks a ton for approving this change request: CHG0030045
@pkliczewski I guess I understand the comment now. I will try to add "a href" tag in the message.

2024-03-15 18:21 UTC, dmartinol commented on escalation-sn/pom.xml
> +<project
Sorry for insisting but you must use quarkus 3 and kogito 2.44.0.Alpha as Annel is doing in his current PR(please have a look)
We cannot downgrade to previous versions of the platform software

2024-03-15 19:28 UTC, rhkp commented on escalation-sn/README.md
> + 3e9cd0a6-c4c8-4ea1-973a-dbb063279397 | Manager, thanks a ton for approving this change request: CHG0030045
Done, as commented below in another PR.

<img width="519" alt="image" src="https://github.com/parodos-dev/serverless-workflow-examples/assets/87712456/08c69e68-7b59-4ca6-8300-b889b0f6ca93">

2024-03-15 19:32 UTC, dmartinol commented on escalation-sn/README.md
> + 3e9cd0a6-c4c8-4ea1-973a-dbb063279397 | Manager, thanks a ton for approving this change request: CHG0030045
@rhkp I think Piotr is suggesting to use the `actions` field of the notification to set the link: the <a href> tag is not properly rendered in Backstage instead

2024-03-15 19:57 UTC, rhkp commented on escalation-sn/README.md
> + 3e9cd0a6-c4c8-4ea1-973a-dbb063279397 | Manager, thanks a ton for approving this change request: CHG0030045
@dmartinol I agree, that is exactly what I did..

2024-03-15 21:34 UTC, rhkp commented on escalation-sn/pom.xml
> +<project
No worries, done.

2024-03-18 13:08 UTC, rhkp commented on escalation-sn/README.md
> +* After this wait, login to notifications service's postgres database console.
Currently the notifications do not provide simple GET requests to get the notifications and require complex setup of users and JWT tokens to be passed to the API.

2024-03-18 13:09 UTC, rhkp commented on escalation-sn/README.md
> +curl -X POST http://localhost:7007/api/notifications/notifications -H "Content-Type: application/json" -d '{"title": "My message title", "message": "I have nothing to say", "origin": "my-origin", "ta
Currently the notifications do not provide simple GET requests to get the notifications and require complex setup of users and JWT tokens to be passed to the API.

2024-03-18 13:18 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            actions: []
no need to provide empty array, just remove the `actions` entry

2024-03-18 13:18 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            targetGroups: []
no need to provide empty array, just remove the entry

2024-03-18 13:19 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            actions: []
As @pkliczewski mentionned in another comment, would it be possible to add the URL pointing to the change request directly? So the manager could just click on the link and it would be redirected to the change request page on service now

2024-03-18 13:32 UTC, dmartinol reviewed
/lgtm

2024-03-18 13:37 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            targetGroups: []
no need to provide empty array, just remove the entry

2024-03-18 13:39 UTC, gabriel-farache commented on escalation-sn/README.md
> +curl -X POST http://localhost:7007/api/notifications/notifications -H "Content-Type: application/json" -d '{"title": "My message title", "message": "I have nothing to say", "origin": "my-origin", "ta
You sure about that? When I run the following for the default/guest user it works
```
$ curl -XPOST https://backstage-backstage-backstage-system.apps.cluster-5qvth.dynamic.redhatworkshops.io/api/notifications/notifications -H "Content-Type: application/json" -d '{"title": "My message title", "message": "I have nothing to say", "origin": "my-origin", "targetUsers": ["default/guest"]}'
{"messageId":"1647c195-250e-4877-8a5a-d2cb402d239d"}


$ curl -XGET https://backstage-backstage-backstage-system.apps.cluster-5qvth.dynamic.redhatworkshops.io/api/notifications/notifications
[{"id":"1647c195-250e-4877-8a5a-d2cb402d239d","created":"2024-03-18T13:37:46.842Z","isSystem":false,"readByUser":false,"origin":"my-origin","title":"My message title","message":"I have nothing to say","topic":null,"actions":[]}]
```
But maybe for specific non default user it does not work?

2024-03-18 13:39 UTC, gabriel-farache requested changes
One extra minor change about the empty arrays in `targetGroups` that are not necessary otherwise LGTM

2024-03-18 15:05 UTC, rhkp commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            targetGroups: []
We cannot remove it, the workflow fails with `500 - Internal Server error` as shown..

<img width="1203" alt="image" src="https://github.com/parodos-dev/serverless-workflow-examples/assets/87712456/261842cd-c06a-4ddf-8f5e-085c02f663fd">
<img width="1208" alt="image" src="https://github.com/parodos-dev/serverless-workflow-examples/assets/87712456/7813ec94-a96e-4c89-b69a-6f6fd6edfca7">

2024-03-18 15:09 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            targetGroups: []
that's very unexpected, in M2K, there is no `targetGroups` and yet there is no error (https://github.com/parodos-dev/serverless-workflows/blob/main/move2kube/m2k.sw.yml#L116) 
And in the openapi spec, it's not marked as required

2024-03-18 15:13 UTC, rhkp commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            targetGroups: []
M2K does not have targetUsers.

2024-03-18 15:15 UTC, gabriel-farache commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            targetGroups: []
@mareklibra @ydayagi does that mean that if we want to provide `targetUsers` we have to provide `targetGroups` as well?

2024-03-18 15:30 UTC, pkliczewski commented
/lgtm

2024-03-18 15:32 UTC, gabriel-farache approved these changes
Let's merge how it is now

2024-03-18 16:05 UTC, masayag approved these changes

2024-03-18 16:06 UTC, merged

2024-03-19 06:56 UTC, ydayagi commented on escalation-sn/src/main/resources/serviceNowEscalation.sw.yaml
> +            targetGroups: []
@gabriel-farache you are correct. you can either specify an empty array or nothing at all.