AAP Job Launch Workflow
parodos-dev/serverless-workflow-examples pull request #33
Opened 2024-03-15 14:46 UTC by anludke

This PR provides an example to launch a job on Ansible Automation Platform given the job template id and send out notification upon completion on failure or success with job output url.

2024-03-15 14:49 UTC, dmartinol commented on aap-job/pom.xml
> +<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
again, it should inherit from swf-parent project the common configs

2024-03-15 14:51 UTC, dmartinol commented on aap-job/src/main/resources/aap-job.sw.yaml
please attach the svg file as well

2024-03-15 14:52 UTC, dmartinol reviewed
lgtm

2024-03-15 15:11 UTC, anludke commented on aap-job/pom.xml
> +<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
It's inheriting the common configs now but I had to modify the kogito version to `2.44.0.Alpha` in the parent.

2024-03-15 15:11 UTC, anludke commented on aap-job/src/main/resources/aap-job.sw.yaml
Done

2024-03-15 15:42 UTC, gabriel-farache commented on aap-job/src/main/resources/aap-job.sw.yaml
> +            message: '"AAP job workflow id: " + $WORKFLOW.instanceId + " for job template id: " + (.jobTemplateId|tostring) + " succeeded. Click the link for details: " + .launchedJob.outputUrl'
put the url in the `actions` instead so it's clickable, see how it's done in M2K workflow https://github.com/parodos-dev/serverless-workflows/blob/main/move2kube/m2k.sw.yml#L120

2024-03-15 15:43 UTC, gabriel-farache requested changes
One minor change related to provide the URL as `action` in the notification

2024-03-15 16:39 UTC, dmartinol commented on aap-job/pom.xml
> +  <dependencyManagement>
if you want you can remove most of these configuratino since they are inherited from the parent (you can look at the escalation-swf for reference)

2024-03-15 16:41 UTC, dmartinol approved these changes
optional: you can simplify the pom.xml, it could be a good reference for future developers

2024-03-18 11:12 UTC, pkliczewski commented
/lgtm

2024-03-19 08:40 UTC, masayag commented on aap-job/src/main/resources/aap-job.svg
Pls pull this file outside of the jar, next to the README.md, and add a reference to it from the README.md.
It would be better to add an absolute path to it (with HTTP://) so it will be rendered nicely on the website.

2024-03-20 16:10 UTC, merged