FLPATH-597 - Move2Kube SWF
parodos-dev/serverless-workflow-examples pull request #8
Opened 2023-10-13 10:15 UTC by gabriel-farache

This PR add new SWF for Move2Kube.

Doc: https://docs.google.com/document/d/1Byy96FnE2_dyI0ZtT_KilRe7gVvWTyECMkbJ9x8-F9A/edit#heading=h.ds8q4xtkmu64

Currently, we are using a version not yet released of sonataflow based on their `main` branch in order to have bugs fixed allowing the workflow to run without error

We will also need to setup proper CI/CD to test that the M2K workflow is working with real instances of Move2Kube and Github

I had to copy/paste the `kustomise` folder of PR #6, this will need to be changed once we have something official and common to deploy all the infra (Data index and Jobs service)

2023-10-16 09:11 UTC, dmartinol reviewed
As a general comment, this complex workflow would deserve an appropriate explanation of the use case and of the proposed architecture.

2023-10-16 09:11 UTC, dmartinol commented on m2k/m2k-func/src/test/resources/SaveTransformationFunctionTest/output.zip
IIUC, the folder output/test is the result of extracting this file, so you should not add it to git, correct? (maybe add it to .gitignore instead)

2023-10-16 09:11 UTC, dmartinol commented on m2k/serverless-workflow-m2k/README.md
> +# serverless-workflow-m2k
Seems to be the default pom when you run `quarkus create`, right?

2023-10-16 09:11 UTC, dmartinol commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +    operation: rest:post:http://move2kube-svc.default.svc.cluster.local:8080/api/v1/workspaces/{workspace-id}/projects/{project-id}/plan #start-planning
a lot of hardcoding here, good for V1 but we  to parametrize it later

2023-10-16 12:18 UTC, gabriel-farache commented on m2k/README.md
> +```bash
Ok  I'll do it

2023-10-16 12:18 UTC, gabriel-farache commented on m2k/README.md
> +# m2k Project
Ok, I'll take what I wrote in the google docs and put it there

2023-10-16 12:21 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/service/Move2KubeServiceImpl.java
> +import dev.parodos.move2kube.ApiClient;
The move2kube API lib come from https://github.com/gabriel-farache/move2kube-java-client and I did not publish the version I used in the project yet

2023-10-16 12:23 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +    operation: rest:post:http://move2kube-svc.default.svc.cluster.local:8080/api/v1/workspaces/{workspace-id}/projects/{project-id}/plan #start-planning
I tried to use $SECRET (even post on the slack channel) but without success
I definitly want those hard coded addresses removed from the workflow definition

2023-10-16 12:23 UTC, dmartinol commented on m2k/m2k-func/src/main/java/dev/parodos/service/Move2KubeServiceImpl.java
> +import dev.parodos.move2kube.ApiClient;
so, cloning this repo is a prerequisite? can't you instead copy the required code in some utility project within this repo?

2023-10-16 12:27 UTC, gabriel-farache commented on m2k/README.md
> + $ kubectl -n m2k apply -f serverless-workflow-m2k/target/kubernetes/knative.yml
we are supposed to be the `serverless-workflow-m2k` directory already, I'll add a `cd` above and I'll remove the `serverless-workflow-m2k` from the path here

2023-10-17 07:11 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/service/Move2KubeServiceImpl.java
> +import dev.parodos.move2kube.ApiClient;
No, I should release the version, no need to have it locally, I just need to figure out how I can have the permissions to push it

2023-10-17 08:41 UTC, gabriel-farache commented on m2k/README.md
> +kubectl -n m2k patch ksvc serverless-workflow-m2k --type merge -p '{
Yeah, those `patch` commands are good for dev but when we will release, we'll need to provide the manifests with everything ready
Here, we have to patch the knative service as the manifest is generated and I do not want to persist something generated or instructs manual changes in the readme

2023-10-17 09:43 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/service/Move2KubeServiceImpl.java
> +import dev.parodos.move2kube.ApiClient;
I embedded the lib generation in the m2k-func module and I add instruction in the README of the module as well

2023-10-17 09:44 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/README.md
> +# serverless-workflow-m2k
I do not know; I do not used this command

2023-10-17 09:46 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +    operation: rest:post:http://move2kube-svc.default.svc.cluster.local:8080/api/v1/workspaces/{workspace-id}/projects/{project-id}/plan #start-planning
https://redhat-internal.slack.com/archives/C059YMMB664/p1697108205897649
https://redhat-internal.slack.com/archives/C059YMMB664/p1697031433026469?thread_ts=1697027758.123669&cid=C059YMMB664

2023-10-17 10:04 UTC, dmartinol commented on m2k/m2k-func/src/test/resources/SaveTransformationFunctionTest/output.zip
Looks like the `output/test` folder is still there in the latest push. Planning to remove it later?

2023-10-30 14:14 UTC, masayag commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +version: '1.0'
please add also `specVersion` element. It is required for the workflow parsing by tools such as the `kn-workflow gen-manifests`

2023-11-02 08:27 UTC, gabriel-farache commented
> @gabriel-farache do we want to continue work on this PR?

Yes, this can't be released until a new version of sonataflow is released

2023-11-20 14:17 UTC, gabriel-farache commented
> @gabriel-farache now that we have prerelease available is this PR still blocked?

@pkliczewski where do you see that?

2023-11-20 14:19 UTC, pkliczewski commented
@gabriel-farache I tagged you in a slack thread

2023-11-20 15:28 UTC, gabriel-farache commented
> @gabriel-farache I tagged you in a slack thread

@pkliczewski so you are talking about https://redhat-internal.slack.com/archives/C059YMMB664/p1700145699121649?thread_ts=1700055474.502659&cid=C059YMMB664 which points to  version `1.44.0.Final-redhat-00005` which is not there (https://repository.jboss.org/nexus/content/groups/public/org/kie/kogito/kogito-bom/)
I could add this repo in the pom.xml to use this one but I am not sure I want to do that, it's just moving the problem for later and I'll still have to retest everything

2023-11-20 15:34 UTC, pkliczewski commented
@gabriel-farache according to sonata team it should be there. It seems like it was not pushed to the registry. Let's revisit this when it is there.

2023-11-20 15:36 UTC, gabriel-farache commented
> @gabriel-farache according to sonata team it should be there. It seems like it was not pushed to the registry. Let's revisit this when it is there.

@pkliczewski or not... juggling with repo like that does not seems to be a good idea IMO, if we are to deliver something to customer, it shall be on the stable channel, not some back channel with unstable versions

2023-11-20 15:41 UTC, pkliczewski commented
@gabriel-farache we can't wait on stable version because we won't be able to deliver anything. Once sonata team will fix the issue with missing RC version we can make progress and verify that it is working when it is released.

2023-11-20 15:49 UTC, gabriel-farache commented
@pkliczewski What is the point of doing that? I know it's working with what on the main branch, and what/when do we plan to deliver to customer?
IMO this is not the place for such discussion, it should be on the slack or agreed during a meeting so everyone is aware :)

2023-12-12 08:58 UTC, gabriel-farache commented on basic-functions/src/main/java/dev/parodos/utils/Utils.java
> +        String path = "/tmp/getzipFn/" + context.getProcessInstance().getStringId();
you mean the `/tmp` part? Yes, I'll update it to createTempDir instead

2023-12-15 09:33 UTC, pkliczewski commented
@masayag @rgolangh @RichardW98 @gciavarrini please review

2023-12-15 16:31 UTC, gciavarrini requested changes

2023-12-15 16:31 UTC, gciavarrini commented on m2k/m2k-func/src/main/java/dev/parodos/service/GitServiceImpl.java
> +import java.io.OutputStream;
Can you please check the imports?

2023-12-15 16:31 UTC, gciavarrini commented on m2k/m2k-func/src/main/java/dev/parodos/service/GitServiceImpl.java
> +        })
This can be semplified like ``.map(ref -> ref.getName())`

2023-12-15 16:31 UTC, gciavarrini commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +      log.error("Error while retrieving transformation output", e);
Can you please check if there is the need to add a place holder for the error object? 

`log.error("Message: {}", e)`

This appears in several places, and sometimes `e` is appended. For example
 ```java
 log.error("Cannot move transformation output to local git repo " +
                  "(repo {}; transformation: {}; workspace: {}; project: {})",
              input.githubRepo, input.transformId, input.workspaceId, input.projectId, e);```

2023-12-15 18:28 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +      log.error("Error while retrieving transformation output", e);
`e` is not in the placeholders in your sample, there are 4 `{}` and 5 parameters.
The `e` in the end without any placeholder will simply be printed as well, see https://www.baeldung.com/slf4j-log-exceptions for instance :)

2023-12-15 18:29 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/service/GitServiceImpl.java
> +import java.io.OutputStream;
good point, done

2023-12-15 18:31 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/service/GitServiceImpl.java
> +        })
ah yes, java syntactic sugar, nice catch
 I do not know why I wrote that like thatin the first place

2023-12-15 18:31 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +  private CloudEvent createBranch(FunInput input, Path gitDir, Git clonedRepo) {
good catch, I missed the Intelij warning

2023-12-15 18:37 UTC, gabriel-farache commented on basic-functions/src/main/java/dev/parodos/utils/Utils.java
> +        inputStream.close();
> is there a reason to read the byte stream instead of using Files library?
TBH I do not know, I just took what Eloy did on this and i did not take time to review it myself in depth (I should have though)
I fixed that with
```
try (InputStream inputStream = httpConn.getInputStream()) {
            FileUtils.copyInputStreamToFile(inputStream, new File(savePath));
        }
```
We have the Apache Commons IO, let's use that :)

2023-12-15 18:38 UTC, gabriel-farache commented on deployment/kustomize/workflows/m2k/configmaps_m2k.yaml
> +    quarkus.log.category."io.vertx".level = DEBUG
I'll remove this `m2k` folder in the deployment, this was a first try to have m2k run with the sonataflow operator but it will be done via the CI so we don't really need that anymore

2023-12-15 18:43 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +    Files.walk(gitDirectory, 1)
ah yeah, I thought the foreach was doing it but it's not the case, thank you!

2023-12-15 18:55 UTC, gabriel-farache commented on m2k/k8s/kustomize/sonataflow/addons/sonataflow-builder-config.yaml
> +    -Djava.util.logging.manager=org.jboss.logmanager.LogManager\"\nENV JAVA_APP_JAR=\"/deployments/quarkus-run.jar\"\n"
ah, when I started to work on M2K the `deployment` folder was not yet part of the main so I copied it, not that #6  is merged, it's duplicated, good catch I did not remember that and it was invisible to my eyes x))

2023-12-15 18:56 UTC, gabriel-farache commented on m2k/k8s/kustomize/sonataflow/addons/sonataflow-platform.yaml
> +        #        value: org.kie.kogito:kogito-addons-quarkus-jobs-knative-eventing:2.0.0-SNAPSHOT,org.kie.kogito:kogito-addons-quarkus-persistence-jdbc:2.0.0-SNAPSHOT,io.quarkus:quarkus-jdbc-postgres
same as above now that #6 is merged, it's leftover

2023-12-15 18:58 UTC, gabriel-farache commented on m2k/m2k-func/README.md
> +Make sure you have a running instance of move2kube reachable from the cluster.
ok

2023-12-15 19:01 UTC, gabriel-farache commented on m2k/m2k-func/README.md
> +* [m2k-trigger.yaml](k8s/m2k-trigger.yaml) will deploy the triggers related to the expected event and to which the kservice subscribes and rely on to get started
is that better?

2023-12-15 19:02 UTC, gabriel-farache commented on m2k/m2k-func/README.md
> +You should be sending the following request from withing the K8S cluster, to do so, you can for instance run:
I reworded the sentence

2023-12-15 19:05 UTC, gabriel-farache commented on m2k/m2k-func/README.md
> +The URL `http://broker-ingress.knative-eventing.svc.cluster.local/m2k/default` is formatted as follow: `http://broker-ingress.knative-eventing.svc.cluster.local/<namespace>/<broker name>`. If you wer
`If you were to change` bear the necessity of the change, it could be `If you needed to change` => if you have to step outside the given steps (ie: changing the namespace) you'll need to change some config
It's with that spirit of caution that I wrote the sentence like that

Is that OK?

2023-12-15 19:06 UTC, gabriel-farache commented on m2k/m2k-func/README.md
> +You can find the IDs in the URL path, ie: `http://localhost:8080/workspaces/dc555a6b-d85c-4932-add4-dcabfddc2770/projects/9adaa1ca-c628-4a9a-abfe-36ac5ca1610e`
is that better?

2023-12-17 15:04 UTC, masayag reviewed
Had mainly question, overall LGTM.

Additional customization to the properties will have to be done once this project is moved to the serverless-workflows repository.

2023-12-17 15:04 UTC, masayag commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +    operation: rest:post:http://move2kube-svc.default.svc.cluster.local:8080/api/v1/workspaces/{workspace-id}/projects/{project-id}/outputs #start-transformation
is `rest` the way to go here?

2023-12-18 08:18 UTC, gciavarrini commented on m2k/m2k-func/README.md
> +* [m2k-trigger.yaml](k8s/m2k-trigger.yaml) will deploy the triggers related to the expected event and to which the kservice subscribes and rely on to get started
yes, thanks!

2023-12-18 08:19 UTC, gciavarrini commented on m2k/m2k-func/README.md
> +You should be sending the following request from withing the K8S cluster, to do so, you can for instance run:
Ok, but there is a typo now `s/hthe/the/`

2023-12-18 08:21 UTC, gciavarrini commented on m2k/m2k-func/README.md
> +The URL `http://broker-ingress.knative-eventing.svc.cluster.local/m2k/default` is formatted as follow: `http://broker-ingress.knative-eventing.svc.cluster.local/<namespace>/<broker name>`. If you wer
No strong opinion, feel free to use what do you prefer. Now I understand the underlying meaning :)

2023-12-18 08:22 UTC, gabriel-farache commented on m2k/m2k-func/README.md
> +You should be sending the following request from withing the K8S cluster, to do so, you can for instance run:
god damnit!

2023-12-18 08:26 UTC, gabriel-farache commented on m2k/m2k-func/src/main/docker/Dockerfile.jvm
> +FROM registry.access.redhat.com/ubi8/openjdk-17:1.11
I did not updated anything manually as far as I remember

2023-12-18 08:26 UTC, gciavarrini commented on m2k/m2k-func/src/main/java/dev/parodos/service/GitServiceImpl.java
> +        })
That's ok! It's just a cosmetic adjustment! :)

2023-12-18 08:27 UTC, gciavarrini commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +      log.error("Error while retrieving transformation output", e);
You're right! Thank you for checking this!

2023-12-18 08:28 UTC, gabriel-farache commented on m2k/README.md
> +Parodos being totally custom made, we were not limited in any way when interacting with github or move2kube instances.
ok

2023-12-18 08:30 UTC, gciavarrini approved these changes
Overall LGTM.
A minor typo to fix and I'd like to add a couple of nit:
`s/Github/GitHub/` and `s/knative/Knative`

Great work!

2023-12-18 08:36 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +    operation: rest:post:http://move2kube-svc.default.svc.cluster.local:8080/api/v1/workspaces/{workspace-id}/projects/{project-id}/outputs #start-transformation
I tried to use the `spec` function but there was a bug (that was fixed I think, that was few months back...) 
I'll try to use the `spec` instead the `rest`

2023-12-18 08:39 UTC, gabriel-farache commented on basic-functions/src/main/resources/workflow.sw.yaml
> +#   type: rest
I'll remove it, I kept it there as a reference but it's not used anywhere in the workflow so it won't be of any help actually

2023-12-18 08:44 UTC, gabriel-farache commented on basic-functions/src/main/resources/specs/github.json
I kept only `list-global-webhooks`

2023-12-18 13:22 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +    operation: rest:post:http://move2kube-svc.default.svc.cluster.local:8080/api/v1/workspaces/{workspace-id}/projects/{project-id}/outputs #start-transformation
Ok, it's working with `rest` specs :)

2023-12-19 10:31 UTC, dmartinol commented on basic-functions/src/main/resources/workflow.sw.yaml
> +  - name: getURLforBranch
what about `print/dump` instead of `get`?

2023-12-19 10:50 UTC, dmartinol commented on m2k/README.md
> +![m2k.svg](serverless-workflow-m2k/src/main/resources/m2k.svg)
the svg file seems not aligned with the latest SWF definition, could you pls update it?

2023-12-19 11:09 UTC, dmartinol commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +            HEADER_Ce-Id: "5678"
Maybe you can replace the hardcoded ID with another `$WORKFLOW.instanceId`?

2023-12-19 11:12 UTC, dmartinol commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +      eventTimeout: PT3M
Maybe you can also intercept the timeout error (newly introduced in 2.0.0-SNAPSHOT) and react appropriately? Otherwise it will follow the default.
See https://github.com/parodos-dev/serverless-workflow-examples/blob/b6cda642a367983346e0ccf912b197dd5effed8f/escalation-eda/escalation-swf/src/main/resources/ticketEscalation.sw.yaml#L15 and https://github.com/parodos-dev/serverless-workflow-examples/blob/b6cda642a367983346e0ccf912b197dd5effed8f/escalation-eda/escalation-swf/src/main/resources/ticketEscalation.sw.yaml#L76

2023-12-19 11:17 UTC, dmartinol commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +      eventTimeout: PT3M
(of course this can be a future enhancement, but it'd be great if we all adopt the same patterns to prove consistent implementations to the readers)

2023-12-19 11:25 UTC, dmartinol commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +  - name: PrintExitErrorMessage
well done 👍 
Just a pity that these 2 print states share 90% of the same code in their 40 lines. Maybe this is the real use case for a parametric subflow? (can be tracked as an enhancement, no worries)

2023-12-19 11:57 UTC, dmartinol commented on m2k/serverless-workflow-m2k/src/main/resources/specs/mailtrap.yaml
Instead of replicating these files in every workflow project, what about using [maven resources plugin](https://www.baeldung.com/maven-resources-plugin) to copy them from a shared location? (this is yet another task that we can track and plan as an enhancement, WDYT?)

2023-12-19 13:13 UTC, gabriel-farache commented on basic-functions/src/main/resources/specs/github.json
I'll remove the basic-functions folder, it adds nothing to the M2K use case

2023-12-19 13:15 UTC, gabriel-farache commented on m2k/README.md
> +![m2k.svg](serverless-workflow-m2k/src/main/resources/m2k.svg)
good catch, I updated the others but not this one, thx!

2023-12-19 13:18 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +          before: PT5S
Yes but not there, I should move it on the later state `PlanRetrievedCheck` for the default condition in order to have a cool down time before checking again if the plan was created
I'll check if I can move it only in the defaultCondition, otherwise I'll keep it there to avoid quick loops thus using resources needlessly

2023-12-19 13:19 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +  - name: PrintExitErrorMessage
Agree, would be nice to have some "state template" feature

2023-12-19 13:20 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/specs/mailtrap.yaml
I'll give a try; I'll create a `share_specs` folder in the root of the project and copy them in the local project

2023-12-19 13:22 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +      eventTimeout: PT3M
BTW, In real life, the timeout will be much higher, months at least
I'll check to use the latest version with this feature but last time I tried I had some issues running the workflow, thus the needed revision, but I'll try again, can't hurt :)

2023-12-19 14:04 UTC, dmartinol commented on m2k/k8s/m2k-role.yaml
> +  namespace: m2k
can we avoid hardcoding namespaces in the manifests and use Helm/kustomize (or just document the manual step as `oc project <namespace>`)?

2023-12-19 14:44 UTC, dmartinol commented on m2k/k8s/m2k-role.yaml
> +kind: ClusterRole
Please verify the ClusterRole is still needed for the SWF ServiceAccount

2023-12-19 14:57 UTC, dmartinol commented on m2k/m2k-func/move2kubeAPI/openapi.json
there are actually little differences b/w this file and `move2kube.json`, only the base path changes.
can we simplify the repo and keep only one copy?

2023-12-19 15:03 UTC, dmartinol commented on m2k/m2k-func/src/main/resources/application.properties
> +transformation-saved.event.name=transformation_saved_event_type
can we rename these two to clarify it's the event type instead of the name?

2023-12-19 15:09 UTC, dmartinol commented on m2k/m2k-func/src/main/java/dev/parodos/EventGenerator.java
> +  public static CloudEvent<EventGenerator.EventPOJO> createErrorEvent(String workflowCallerId, String message, String source) {
shouldn't we have a `createSuccessfulEvent` method as well and move the definition of the successful event type to this class?

2023-12-19 15:15 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/EventGenerator.java
> +  public static CloudEvent<EventGenerator.EventPOJO> createErrorEvent(String workflowCallerId, String message, String source) {
Yeah but it would be the exact same code as in `EventGenerator.createCloudEvent` 
I could add a method that just call it but it would be boilerplate
The  `createErrorEvent` is there so the user do not have to bother finding the right format for the `data`, it just gives the message and the method wraps it

2023-12-19 15:17 UTC, gabriel-farache commented on m2k/m2k-func/src/main/resources/application.properties
> +transformation-saved.event.name=transformation_saved_event_type
I'll rename it both there and in the workflow definition file, I used this naming to be similar to what was done in the example but i agree with you, it's not good; I'll strtip the `_event` part

2023-12-19 15:28 UTC, gabriel-farache commented on m2k/k8s/m2k-role.yaml
> +kind: ClusterRole
Ok, so the cluster role is needed, if it's not there, I get
```
Service Discovery has failed on property [kogito.jobs-service.url=kubernetes:services.v1/default/jobs-service-service]: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1:443/api/v1/namespaces/default/services/jobs-service-service. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services "jobs-service-service" is forbidden: User "system:serviceaccount:m2k:serverless-workflow-m2k" cannot get resource "services" in API group "" in the namespace "default".
```
If I change `kogito.jobs-service.url=${kubernetes:services.v1/default/jobs-service-service}` to `kogito.jobs-service.url=jobs-service-service.default.svc.cluster.local` I don't need it anymore

I'll do the change as I am not using the discovery service anywhere else

2023-12-19 15:29 UTC, dmartinol commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +    FileUtils.copyDirectory(finalPath.resolve(Paths.get("source")).toFile(),
maybe use a for-loop to repeat the same copy command n times?

2023-12-19 15:34 UTC, dmartinol commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +        CloudEvent workflowCallerId = createBranch(input, clonedRepo);
maybe `workflowCallerId` is not an appropriate variable name (can be confused with the input field)

2023-12-19 15:35 UTC, gabriel-farache commented on m2k/k8s/m2k-role.yaml
> +  namespace: m2k
I'll remove the clusterrole

2023-12-19 15:37 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +        CloudEvent workflowCallerId = createBranch(input, clonedRepo);
I'll rename it to `errorEvent`

2023-12-19 15:40 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/SaveTransformationFunction.java
> +    FileUtils.copyDirectory(finalPath.resolve(Paths.get("source")).toFile(),
I'll create 
```
  public static final  String[] MOVE2KUBE_OUTPUT_DIRECTORIES_TO_SAVE = new String[]{"source","deploy","scripts" };
```
and iterate over it

2023-12-19 15:42 UTC, gabriel-farache commented on m2k/m2k-func/move2kubeAPI/openapi.json
This file should no be persisted, it's a mistake, the `make install` will download the latest version from move2kube repo and create the API from it

2023-12-19 15:49 UTC, dmartinol commented on m2k/m2k-func/src/main/java/dev/parodos/service/Move2KubeServiceImpl.java
> +    planApi.startPlanning(workspaceId, projectId);
The build fails here because of a missing parameter, even if it's marked as not required in the `openapi.json`:
```
Move2KubeServiceImpl.java:[42,12] no suitable method found for startPlanning(java.lang.String,java.lang.String)
```
Can you please try the same on your side?

2023-12-19 15:59 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +          before: PT5S
Nervermind, this is `StartPlanning` state, not `GetPlanning`, so no this sleep should not be there
I tried to put the sleep in the defaultCondition but it did not worked:
```
[ERROR]         [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: org.kie.kogito.codegen.process.ProcessCodegenException: Processes with errors are Invalid process: '/home/gabriel/git/parodos_stuff_v2/serverless-workflow-examples/m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml'. Found error: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "sleep" (class io.serverlessworkflow.api.defaultdef.DefaultConditionDefinition), not marked as ignorable (2 known properties: "end", "transition"])
[ERROR]  at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.serverlessworkflow.api.Workflow["states"]->java.util.ArrayList[2]->io.serverlessworkflow.api.states.SwitchState["defaultCondition"]->io.serverlessworkflow.api.defaultdef.DefaultConditionDefinition["sleep"])

``` 
So I'll be keeping the sleep but I'll reduce it to 2 seconds

2023-12-19 16:07 UTC, dmartinol commented on m2k/m2k-func/src/main/java/dev/parodos/EventGenerator.java
> +  public static CloudEvent<EventGenerator.EventPOJO> createErrorEvent(String workflowCallerId, String message, String source) {
I mean: the event type resolution for the error event is in this class, whole the event type resolution for the successful event is in the other class using these methods. Isn't that a bit inconsistent?
```java
  @ConfigProperty(name = "transformation-saved.event.name")
  private String transformationSavedEventName;
```

2023-12-19 16:16 UTC, dmartinol commented
overall, LGTM, but in order to move it to the final examples repo, we need to review these aspects IMO (the same probably applies to the `escalation-eda` application):
- SWF should be reviewed using the flat layout instead of the quarkus one, this would remove a lot of overhead
- SWF deployment must be consistent with the other examples in https://github.com/parodos-dev/serverless-workflows and use operator-based deployment instead of the kubernetes deployment
- Generally speaking, the documentation should be simplified and focused on describing the implemented functionalities, the architecture and the deployment and user instructions (possibly using `kn-workflow` functions as much as possible)
- Maybe some sections may be taken out from the workflow's README and moved to a common README
- Still we need to design how the other software components (the Knative functions and eventing resources) can be managed by the common-purpose pipeline

@masayag @rgolangh

2023-12-19 16:32 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/specs/mailtrap.yaml
I am putting the shared specs in the `specs/shared` folder of the current project
The folder is deleted when calling clean and is added to the gitignore

2023-12-19 20:03 UTC, gabriel-farache commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +      eventTimeout: PT3M
Not sure this is needed to do this timeout error management here, per the example https://sonataflow.org/serverlessworkflow/latest/use-cases/timeout-showcase-example.html, if the timeout expire, the switch will go to the default condition, I'll add `TransformationTimedOut` to make that clear

2023-12-19 20:08 UTC, gabriel-farache commented on m2k/m2k-func/src/main/java/dev/parodos/EventGenerator.java
> +  public static CloudEvent<EventGenerator.EventPOJO> createErrorEvent(String workflowCallerId, String message, String source) {
You got me on this one, I'll do it

2023-12-19 20:18 UTC, gabriel-farache commented
@dmartinol by  
> the final examples repo 
You mean https://github.com/parodos-dev/serverless-workflows, right? On this point I agree, some changes will be needed (ie: removing the email sending)

I am still not sure if this repo (this one the PR, https://github.com/parodos-dev/serverless-workflow-examples) will be of any use once we get the other one ready and running, except probably for developer oriented usage (debugging when bugs, ...)

Using the operator will be nice too but for that we need a release with the changes from the 2.0.0-SNAPSHOT that we are using (ie: the fixes applied after bugs were found doing this workflow) otherwise it won't work

For the Docs/README, yes some part could be shared between all projects but we need also to provide for each projects, the steps to have it running locally and possibly how to debug it so I am not sure how we can reduce the amount of what we are writing. In my case, I have 3 README, I could reduce it to 1 in the main project but for the knative function, I want to provide as much information as possible for any one taking the project and looking to improve or fix things

2023-12-20 08:40 UTC, dmartinol commented on m2k/serverless-workflow-m2k/src/main/resources/m2k.sw.yml
> +      eventTimeout: PT3M
if you mean to transition by default to `TransformationTimedOut`, it might be misleading as all the uncaught errors would follow the same default.
so I agree that this can be postponed so I'll add one more point to the final comment below for this reason. you can resolve this comment

2023-12-21 07:17 UTC, dmartinol commented
@masayag can we LGTM now?

2023-12-21 07:36 UTC, masayag approved these changes

2023-12-21 07:36 UTC, merged